//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectoSemestralBiblioteca.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Libro()
        {
            this.prestamo = new HashSet<prestamo>();
            this.Venta = new HashSet<Venta>();
        }
    
        public int idLibro { get; set; }
        public string tituloLibro { get; set; }
        public Nullable<int> idEditorial { get; set; }
        public Nullable<int> idAutor { get; set; }
        public Nullable<int> idGenero { get; set; }
        public Nullable<int> numPaginas { get; set; }
        public Nullable<System.DateTime> fechaEdicion { get; set; }
        public Nullable<int> idCosto { get; set; }
        public string isbn { get; set; }
        public string idioma { get; set; }
        public Nullable<int> idEjemplar { get; set; }
        public Nullable<int> idEstante { get; set; }
    
        public virtual Autor Autor { get; set; }
        public virtual costo costo { get; set; }
        public virtual Editorial Editorial { get; set; }
        public virtual Ejemplar Ejemplar { get; set; }
        public virtual Estante Estante { get; set; }
        public virtual Genero Genero { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prestamo> prestamo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Venta> Venta { get; set; }
    }
}
