//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectoSemestralBiblioteca.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public int idVenta { get; set; }
        public Nullable<int> idLibro { get; set; }
        public Nullable<System.DateTime> fechaVenta { get; set; }
        public string idUsuario { get; set; }
        public Nullable<int> totalVenta { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Libro Libro { get; set; }
    }
}
